# Generated by Django 5.2.10 on 2026-02-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='clicks',
            field=models.PositiveIntegerField(default=False),
        ),
    ]
